stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  tags:
    - myserver
  script:
    - echo "Build docker image"
    - docker build -t "$PROJECT_NAME:ci_job_$CI_PIPELINE_ID" .
    - docker image ls

deploy:
  stage: deploy
  only:
    - master
  tags:
    - myserver
  script:
    - echo "Stop running container"
    - docker stop $PROJECT_NAME && docker rm $PROJECT_NAME || true  # $PROJECT_NAME is ci variable
    - echo "Start docker container"
    - docker run --restart=unless-stopped --name=$PROJECT_NAME -d -p 8112:8000 "$PROJECT_NAME:ci_job_$CI_PIPELINE_ID"
    - docker ps
    - rm -f *.jar && docker cp $PROJECT_NAME:/app/SpringApplication.jar $PROJECT_NAME.jar
    - old_images=$(docker image ls | grep electricbackend | grep -v $(docker image ls | grep electricbackend | awk '{print $2}' | awk -F_ '{print $3}' | sort -rn | head -2 | xargs | sed 's/ /\\|/g') | awk '{print $3}') ; if [ -n "$old_images" ]; then docker image rm $old_images ; fi ; unset old_images
    - docker image ls
  artifacts:
    paths:
      - $PROJECT_NAME.jar
