server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://49.235.193.150:3306/db_course_2021?useUnicode=true&characterEncoding=utf8
    username: # runtime argument
    password: # runtime argument
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 4KB
      max-file-size: 8MB
      max-request-size: 8MB
file: # customized configuration key
  file-dir: /storage